# https://github.com/devcontainers/templates/blob/main/src/docker-existing-docker-compose/.devcontainer/docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: liquibase_postgres_container
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - default
  liquibase:
    build: 
       context: .
       dockerfile: build/Dockerfile
       args:
        USERNAME: postgres
        PASSWORD: postgres
    container_name: liquibase_app_container
    depends_on:
        - db
    networks:
      - default
    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      #- .:/workspace:cached
      - .:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  postgres-data:
networks:
  default: