# https://github.com/devcontainers/templates/blob/main/src/docker-existing-docker-compose/.devcontainer/docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: liquibase_postgres
    restart: unless-stopped
    volumes:
      - postgres-data-liquibase:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - default
volumes:
  postgres-data-liquibase:
networks:
  default: